### ISSUE TITLE
name participles dropped when reading from cff

### ISSUE THREAD

**Issue by burgerga** [ropensci/handlr#28]
See https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionspersonname-particle

```yaml
authors:
  - family-names: Humboldt
    given-names: Alexander
    name-particle: von
```

will result in 

```r
[[1]]
[[1]]$type
[1] "Person"

[[1]]$name
[1] "Alexander Humboldt"

[[1]]$givenName
[1] "Alexander"

[[1]]$familyName
[1] "Humboldt"
```

instead of `"Alexander von Humboldt"`.

Particularly problematic when working with Dutch names ;)
